apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: podinfo-secret
  namespace: podinfo
spec:
  hostAPI: https://app.infisical.com/api
  syncConfig:
    resyncInterval: 60s
    instantUpdates: false
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infisical-auth
        secretNamespace: infisical-operator
      secretsScope:
        projectSlug: prod
        envSlug: prod
        secretsPath: /podinfo/test
  managedKubeSecretReferences:
    - secretName: podinfo-infisical-secret
      secretNamespace: podinfo
      creationPolicy: Owner
