---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: external-dns
spec:
  encryptedData:
    api-token: <will-be-filled-by-sealed-secrets>
  template:
    metadata:
      name: cloudflare-api-token
      namespace: external-dns
