---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: infisical-auth
  namespace: infisical-operator
spec:
  encryptedData:
    clientId: <will-be-filled-by-sealed-secrets>
    clientSecret: <will-be-filled-by-sealed-secrets>
  template:
    metadata:
      name: infisical-auth
      namespace: infisical-operator
