apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - cloudflare-external-dns.yaml
  - cloudflare-cert-manager.yaml
  - r2-cnpg-backup.yaml
  - infisical-auth.yaml
