---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: s3-credentials
  namespace: databases
spec:
  encryptedData:
    S3_ACCESS_KEY_ID: <will-be-filled-by-sealed-secrets>
    S3_ACCESS_KEY_SECRET: <will-be-filled-by-sealed-secrets>
  template:
    metadata:
      name: s3-credentials
      namespace: databases
